import { agoraIso, historicoPara, nomesIguais } from '../cliente/solicitacao.util';
import type { ClienteSolicitacao, FuncionarioResumo, SolicitacaoFuncionario } from './funcionario.models';

const JOAO: ClienteSolicitacao = {
  id: 1,
  nome: 'Joao',
  email: 'joao@manutencao.com',
  cpf: '123.456.789-01',
  telefone: '(41) 99999-0001',
  endereco: 'Rua das Flores, 100, Centro, Curitiba/PR, 80010-000',
};

const JOSE: ClienteSolicitacao = {
  id: 2,
  nome: 'Jose',
  email: 'jose@manutencao.com',
  cpf: '123.456.789-02',
  telefone: '(41) 99999-0002',
  endereco: 'Rua das Flores, 100, Centro, Curitiba/PR, 80010-000',
};

const JOANA: ClienteSolicitacao = {
  id: 3,
  nome: 'Joana',
  email: 'joana@manutencao.com',
  cpf: '123.456.789-03',
  telefone: '(41) 99999-0003',
  endereco: 'Rua das Flores, 100, Centro, Curitiba/PR, 80010-000',
};

const JOAQUINA: ClienteSolicitacao = {
  id: 4,
  nome: 'Joaquina',
  email: 'joaquina@manutencao.com',
  cpf: '123.456.789-04',
  telefone: '(41) 99999-0004',
  endereco: 'Rua das Flores, 100, Centro, Curitiba/PR, 80010-000',
};

export const CLIENTES_DEMO: ClienteSolicitacao[] = [JOAO, JOSE, JOANA, JOAQUINA];

export function clienteDemoPorNome(nome: string, email?: string): ClienteSolicitacao | undefined {
  const emailNorm = email?.trim().toLowerCase();
  return CLIENTES_DEMO.find((cliente) =>
    nomesIguais(cliente.nome, nome)
    || Boolean(emailNorm && cliente.email.toLowerCase() === emailNorm),
  );
}

export const FUNCIONARIOS_DEMO: FuncionarioResumo[] = [
  { id: 1, nome: 'Maria', email: 'maria@manutencao.com' },
  { id: 2, nome: 'Mario', email: 'mario@manutencao.com' },
];

type Base = Omit<SolicitacaoFuncionario, 'historico'> & { historico?: SolicitacaoFuncionario['historico'] };

const BASE: Base[] = [
  {
    id: 1,
    dataHoraAbertura: '2026-01-12T14:10:00',
    descricaoEquipamento: 'Lenovo ThinkPad',
    descricaoDefeito: 'Nao carrega mesmo ligado na tomada.',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
    cliente: JOAQUINA,
    funcionarioDestino: null,
  },
  {
    id: 2,
    dataHoraAbertura: '2026-01-20T10:00:00',
    descricaoEquipamento: 'Dell XPS 13',
    descricaoDefeito: 'Dobradica quebrada apos queda.',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 1100,
    cliente: JOANA,
    funcionarioDestino: null,
    descricaoManutencao: 'Troca da dobradica e alinhamento da tampa.',
    orientacoesCliente: 'Evitar abrir a tela alem de 120 graus.',
  },
  {
    id: 3,
    dataHoraAbertura: '2026-02-05T08:40:00',
    descricaoEquipamento: 'PC Gamer Ryzen',
    descricaoDefeito: 'Nao da video ao ligar.',
    categoria: 'Desktop',
    estado: 'ABERTA',
    valorOrcamento: null,
    cliente: JOSE,
    funcionarioDestino: null,
  },
  {
    id: 4,
    dataHoraAbertura: '2026-02-08T09:45:00',
    descricaoEquipamento: 'Brother DCP',
    descricaoDefeito: 'Nao puxa papel da bandeja.',
    categoria: 'Impressora',
    estado: 'PAGA',
    valorOrcamento: 270,
    cliente: JOANA,
    funcionarioDestino: null,
    descricaoManutencao: 'Limpeza do rolete e troca do kit de alimentacao.',
    orientacoesCliente: 'Usar papel dentro da gramatura recomendada.',
  },
  {
    id: 5,
    dataHoraAbertura: '2026-02-10T09:12:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    descricaoDefeito: 'Nao liga apos queda.',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
    cliente: JOAO,
    funcionarioDestino: null,
  },
  {
    id: 6,
    dataHoraAbertura: '2026-02-12T11:30:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    descricaoDefeito: 'Tela com listras verticais.',
    categoria: 'Notebook',
    estado: 'APROVADA',
    valorOrcamento: 890,
    cliente: JOAO,
    funcionarioDestino: null,
  },
  {
    id: 7,
    dataHoraAbertura: '2026-02-14T15:05:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    descricaoDefeito: 'Teclado com teclas falhando.',
    categoria: 'Notebook',
    estado: 'ARRUMADA',
    valorOrcamento: 640,
    cliente: JOAO,
    funcionarioDestino: null,
    descricaoManutencao: 'Substituicao do teclado e testes de teclas.',
    orientacoesCliente: 'Evitar liquidos sobre o teclado.',
  },
  {
    id: 8,
    dataHoraAbertura: '2026-02-16T18:20:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    descricaoDefeito: 'Troca de bateria.',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 450,
    cliente: JOAO,
    funcionarioDestino: null,
    descricaoManutencao: 'Troca da bateria original.',
    orientacoesCliente: 'Calibrar a carga nas primeiras 3 ciclos.',
  },
  {
    id: 9,
    dataHoraAbertura: '2026-02-19T19:47:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    descricaoDefeito: 'Troca de SSD.',
    categoria: 'Notebook',
    estado: 'ORCADA',
    valorOrcamento: 1250,
    cliente: JOAO,
    funcionarioDestino: null,
  },
  {
    id: 10,
    dataHoraAbertura: '2026-02-21T17:10:00',
    descricaoEquipamento: 'Teclado mecanico',
    descricaoDefeito: 'Tecla W travando.',
    categoria: 'Teclado',
    estado: 'ORCADA',
    valorOrcamento: 210,
    cliente: JOSE,
    funcionarioDestino: null,
  },
  {
    id: 11,
    dataHoraAbertura: '2026-02-27T16:55:00',
    descricaoEquipamento: 'HP Pavilion',
    descricaoDefeito: 'Barulho constante no cooler.',
    categoria: 'Desktop',
    estado: 'ORCADA',
    valorOrcamento: 410,
    cliente: JOAQUINA,
    funcionarioDestino: null,
  },
  {
    id: 12,
    dataHoraAbertura: '2026-03-02T10:15:00',
    descricaoEquipamento: 'iMac 24',
    descricaoDefeito: 'Nao reconhece o monitor interno.',
    categoria: 'Desktop',
    estado: 'PAGA',
    valorOrcamento: 980,
    cliente: JOAO,
    funcionarioDestino: null,
    descricaoManutencao: 'Reparo da placa de video e testes de imagem.',
    orientacoesCliente: 'Atualizar o macOS apos a retirada.',
  },
  {
    id: 13,
    dataHoraAbertura: '2026-03-04T12:00:00',
    descricaoEquipamento: 'Mouse sem fio',
    descricaoDefeito: 'Bateria nao carrega.',
    categoria: 'Mouse',
    estado: 'APROVADA',
    valorOrcamento: 150,
    cliente: JOSE,
    funcionarioDestino: null,
  },
  {
    id: 14,
    dataHoraAbertura: '2026-03-08T14:40:00',
    descricaoEquipamento: 'HP LaserJet',
    descricaoDefeito: 'Atolamento constante de papel.',
    categoria: 'Impressora',
    estado: 'REDIRECIONADA',
    valorOrcamento: 320,
    cliente: JOAO,
    funcionarioDestino: 'Mario',
  },
  {
    id: 15,
    dataHoraAbertura: '2026-03-11T16:22:00',
    descricaoEquipamento: 'Logitech MX',
    descricaoDefeito: 'Scroll com falha intermitente.',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 180,
    cliente: JOAO,
    funcionarioDestino: null,
    motivoRejeicao: 'Valor acima do esperado para a peca.',
  },
  {
    id: 16,
    dataHoraAbertura: '2026-03-15T11:25:00',
    descricaoEquipamento: 'Epson EcoTank',
    descricaoDefeito: 'Manchas na impressao.',
    categoria: 'Impressora',
    estado: 'ARRUMADA',
    valorOrcamento: 390,
    cliente: JOSE,
    funcionarioDestino: null,
    descricaoManutencao: 'Limpeza dos cabecotes e alinhamento.',
    orientacoesCliente: 'Executar limpeza leve a cada 30 dias.',
  },
  {
    id: 17,
    dataHoraAbertura: '2026-03-18T09:05:00',
    descricaoEquipamento: 'Keychron K2',
    descricaoDefeito: 'Nao conecta no Bluetooth.',
    categoria: 'Teclado',
    estado: 'ABERTA',
    valorOrcamento: null,
    cliente: JOAO,
    funcionarioDestino: null,
  },
  {
    id: 18,
    dataHoraAbertura: '2026-03-22T19:18:00',
    descricaoEquipamento: 'Apple Magic Mouse',
    descricaoDefeito: 'Sensor falhando em superficies claras.',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 240,
    cliente: JOANA,
    funcionarioDestino: null,
    motivoRejeicao: 'Prefiro aguardar peca original.',
  },
  {
    id: 19,
    dataHoraAbertura: '2026-03-29T10:08:00',
    descricaoEquipamento: 'Canon Pixma',
    descricaoDefeito: 'Cabeca de impressao com falhas.',
    categoria: 'Impressora',
    estado: 'ARRUMADA',
    valorOrcamento: 520,
    cliente: JOAQUINA,
    funcionarioDestino: null,
    descricaoManutencao: 'Substituicao da cabeca e teste de cores.',
    orientacoesCliente: 'Nao deixar a impressora parada por longos periodos.',
  },
  {
    id: 20,
    dataHoraAbertura: '2026-04-01T13:50:00',
    descricaoEquipamento: 'Dell Optiplex',
    descricaoDefeito: 'Superaquecimento apos 20 minutos de uso.',
    categoria: 'Desktop',
    estado: 'ORCADA',
    valorOrcamento: 760,
    cliente: JOAO,
    funcionarioDestino: null,
  },
  {
    id: 21,
    dataHoraAbertura: '2026-04-03T08:30:00',
    descricaoEquipamento: 'Logitech MX Keys',
    descricaoDefeito: 'Teclas com iluminacao apagada.',
    categoria: 'Teclado',
    estado: 'REDIRECIONADA',
    valorOrcamento: 330,
    cliente: JOANA,
    funcionarioDestino: 'Maria',
  },
  {
    id: 22,
    dataHoraAbertura: '2026-04-06T15:33:00',
    descricaoEquipamento: 'Acer Aspire 5',
    descricaoDefeito: 'Wifi instavel em casa.',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 300,
    cliente: JOAQUINA,
    funcionarioDestino: null,
    descricaoManutencao: 'Troca da antena wireless.',
    orientacoesCliente: 'Atualizar o driver de rede no Windows.',
  },
];

function comHistorico(item: Base): SolicitacaoFuncionario {
  const historico = item.historico ?? historicoPara(item.estado, item.dataHoraAbertura, item.cliente.nome, {
    funcionarioDestino: item.funcionarioDestino,
  });
  return { ...item, historico };
}

export const SOLICITACOES_FUNCIONARIO_DEMO: SolicitacaoFuncionario[] = [
  ...BASE.map(comHistorico),
  comHistorico({
    id: 23,
    dataHoraAbertura: agoraIso(),
    descricaoEquipamento: 'Notebook Dell Inspiron',
    descricaoDefeito: 'Nao inicia o sistema operacional.',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
    cliente: JOAO,
    funcionarioDestino: null,
  }),
];
