import type { SolicitacaoDetalhe } from './solicitacao.service';
import { historicoPara } from './solicitacao.util';

type BaseDemo = Omit<SolicitacaoDetalhe, 'historico'> & { historico?: SolicitacaoDetalhe['historico'] };

const BASE: BaseDemo[] = [
  {
    id: 1,
    dataHoraAbertura: '2026-01-12T14:10:00',
    descricaoEquipamento: 'Lenovo ThinkPad',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
    clienteNome: 'Joao',
    descricaoDefeito: 'Nao carrega mesmo ligado na tomada.',
  },
  {
    id: 2,
    dataHoraAbertura: '2026-01-20T10:00:00',
    descricaoEquipamento: 'Dell XPS 13',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 1100,
    clienteNome: 'Jose',
    descricaoDefeito: 'Dobradica quebrada apos queda.',
    descricaoManutencao: 'Troca da dobradica e alinhamento da tampa.',
    orientacoesCliente: 'Evitar abrir a tela alem de 120 graus.',
  },
  {
    id: 3,
    dataHoraAbertura: '2026-02-05T08:40:00',
    descricaoEquipamento: 'PC Gamer Ryzen',
    categoria: 'Desktop',
    estado: 'ABERTA',
    valorOrcamento: null,
    clienteNome: 'Joana',
    descricaoDefeito: 'Nao da video ao ligar.',
  },
  {
    id: 4,
    dataHoraAbertura: '2026-02-08T09:45:00',
    descricaoEquipamento: 'Brother DCP',
    categoria: 'Impressora',
    estado: 'PAGA',
    valorOrcamento: 270,
    clienteNome: 'Joaquina',
    descricaoDefeito: 'Nao puxa papel da bandeja.',
    descricaoManutencao: 'Limpeza do rolete e troca do kit de alimentacao.',
    orientacoesCliente: 'Usar papel dentro da gramatura recomendada.',
  },
  {
    id: 5,
    dataHoraAbertura: '2026-02-10T09:12:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
    clienteNome: 'Joao',
    descricaoDefeito: 'Nao liga apos queda.',
  },
  {
    id: 6,
    dataHoraAbertura: '2026-02-12T11:30:00',
    descricaoEquipamento: 'Acer Aspire 5',
    categoria: 'Notebook',
    estado: 'APROVADA',
    valorOrcamento: 890,
    clienteNome: 'Jose',
    descricaoDefeito: 'Tela com listras verticais.',
  },
  {
    id: 7,
    dataHoraAbertura: '2026-02-14T15:05:00',
    descricaoEquipamento: 'Keychron K2',
    categoria: 'Teclado',
    estado: 'ARRUMADA',
    valorOrcamento: 210,
    clienteNome: 'Joana',
    descricaoDefeito: 'Nao conecta no Bluetooth.',
    descricaoManutencao: 'Atualizacao de firmware e troca do modulo wireless.',
    orientacoesCliente: 'Reconectar o teclado nas preferencias de Bluetooth.',
  },
  {
    id: 8,
    dataHoraAbertura: '2026-02-16T18:20:00',
    descricaoEquipamento: 'HP Pavilion',
    categoria: 'Desktop',
    estado: 'FINALIZADA',
    valorOrcamento: 450,
    clienteNome: 'Joaquina',
    descricaoDefeito: 'Barulho constante no cooler.',
    descricaoManutencao: 'Troca do cooler e limpeza interna.',
    orientacoesCliente: 'Manter o gabinete ventilado.',
  },
  {
    id: 9,
    dataHoraAbertura: '2026-02-19T19:47:00',
    descricaoEquipamento: 'ASUS ROG Zephyrus',
    categoria: 'Notebook',
    estado: 'ORCADA',
    valorOrcamento: 1250,
    clienteNome: 'Joao',
    descricaoDefeito: 'Superaquecimento em jogos.',
  },
  {
    id: 10,
    dataHoraAbertura: '2026-02-21T17:10:00',
    descricaoEquipamento: 'Teclado mecanico',
    categoria: 'Teclado',
    estado: 'ORCADA',
    valorOrcamento: 180,
    clienteNome: 'Jose',
    descricaoDefeito: 'Tecla W travando.',
  },
  {
    id: 11,
    dataHoraAbertura: '2026-02-27T16:55:00',
    descricaoEquipamento: 'iMac 24',
    categoria: 'Desktop',
    estado: 'ORCADA',
    valorOrcamento: 410,
    clienteNome: 'Joana',
    descricaoDefeito: 'Nao reconhece o monitor interno.',
  },
  {
    id: 12,
    dataHoraAbertura: '2026-03-02T10:15:00',
    descricaoEquipamento: 'Dell Optiplex',
    categoria: 'Desktop',
    estado: 'PAGA',
    valorOrcamento: 980,
    clienteNome: 'Joaquina',
    descricaoDefeito: 'Superaquecimento apos 20 minutos de uso.',
    descricaoManutencao: 'Troca da pasta termica e limpeza do dissipador.',
    orientacoesCliente: 'Evitar obstruir as saidas de ar.',
  },
  {
    id: 13,
    dataHoraAbertura: '2026-03-04T12:00:00',
    descricaoEquipamento: 'Mouse sem fio',
    categoria: 'Mouse',
    estado: 'APROVADA',
    valorOrcamento: 150,
    clienteNome: 'Joao',
    descricaoDefeito: 'Bateria nao carrega.',
  },
  {
    id: 14,
    dataHoraAbertura: '2026-03-08T14:40:00',
    descricaoEquipamento: 'HP LaserJet',
    categoria: 'Impressora',
    estado: 'REDIRECIONADA',
    valorOrcamento: 320,
    clienteNome: 'Jose',
    funcionarioDestino: 'Mario',
    descricaoDefeito: 'Atolamento constante de papel.',
  },
  {
    id: 15,
    dataHoraAbertura: '2026-03-11T16:22:00',
    descricaoEquipamento: 'Logitech MX',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 180,
    clienteNome: 'Joana',
    descricaoDefeito: 'Scroll com falha intermitente.',
    motivoRejeicao: 'Valor acima do esperado para a peca.',
  },
  {
    id: 16,
    dataHoraAbertura: '2026-03-15T11:25:00',
    descricaoEquipamento: 'Epson EcoTank',
    categoria: 'Impressora',
    estado: 'ARRUMADA',
    valorOrcamento: 390,
    clienteNome: 'Joaquina',
    descricaoDefeito: 'Manchas na impressao.',
    descricaoManutencao: 'Limpeza dos cabeçotes e alinhamento.',
    orientacoesCliente: 'Executar limpeza leve a cada 30 dias.',
  },
  {
    id: 17,
    dataHoraAbertura: '2026-03-22T19:18:00',
    descricaoEquipamento: 'Apple Magic Mouse',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 240,
    clienteNome: 'Joao',
    descricaoDefeito: 'Sensor falhando em superficies claras.',
    motivoRejeicao: 'Prefiro aguardar peca original.',
  },
  {
    id: 18,
    dataHoraAbertura: '2026-03-29T10:08:00',
    descricaoEquipamento: 'Canon Pixma',
    categoria: 'Impressora',
    estado: 'ARRUMADA',
    valorOrcamento: 520,
    clienteNome: 'Jose',
    descricaoDefeito: 'Cabeca de impressao com falhas.',
    descricaoManutencao: 'Substituicao da cabeca e teste de cores.',
    orientacoesCliente: 'Nao deixar a impressora sem uso por longos periodos.',
  },
  {
    id: 19,
    dataHoraAbertura: '2026-04-03T08:30:00',
    descricaoEquipamento: 'Logitech MX Keys',
    categoria: 'Teclado',
    estado: 'REDIRECIONADA',
    valorOrcamento: 330,
    clienteNome: 'Joana',
    funcionarioDestino: 'Maria',
    descricaoDefeito: 'Teclas com iluminacao apagada.',
  },
  {
    id: 20,
    dataHoraAbertura: '2026-04-06T15:33:00',
    descricaoEquipamento: 'Samsung Galaxy Book',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 300,
    clienteNome: 'Joaquina',
    descricaoDefeito: 'Wifi instavel em casa.',
    descricaoManutencao: 'Troca da antena wireless.',
    orientacoesCliente: 'Atualizar o driver de rede no Windows.',
  },
];

export const SOLICITACOES_DEMO: SolicitacaoDetalhe[] = BASE.map((item) => ({
  ...item,
  historico: item.historico ?? historicoPara(item.estado, item.dataHoraAbertura),
}));
