import type { SolicitacaoResumo } from './solicitacao.service';

export const SOLICITACOES_DEMO: SolicitacaoResumo[] = [
  {
    id: 1,
    dataHoraAbertura: '2026-02-10T09:12:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
  },
  {
    id: 2,
    dataHoraAbertura: '2026-02-12T11:30:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'APROVADA',
    valorOrcamento: 890,
  },
  {
    id: 3,
    dataHoraAbertura: '2026-02-14T15:05:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'ARRUMADA',
    valorOrcamento: 640,
  },
  {
    id: 4,
    dataHoraAbertura: '2026-02-16T18:20:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 450,
  },
  {
    id: 5,
    dataHoraAbertura: '2026-02-19T19:47:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'ORCADA',
    valorOrcamento: 1250,
  },
  {
    id: 6,
    dataHoraAbertura: '2026-03-02T10:15:00',
    descricaoEquipamento: 'iMac 24',
    categoria: 'Desktop',
    estado: 'PAGA',
    valorOrcamento: 980,
  },
  {
    id: 7,
    dataHoraAbertura: '2026-03-08T14:40:00',
    descricaoEquipamento: 'HP LaserJet',
    categoria: 'Impressora',
    estado: 'REDIRECIONADA',
    valorOrcamento: 320,
  },
  {
    id: 8,
    dataHoraAbertura: '2026-03-11T16:22:00',
    descricaoEquipamento: 'Logitech MX',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 180,
  },
  {
    id: 9,
    dataHoraAbertura: '2026-03-18T09:05:00',
    descricaoEquipamento: 'Keychron K2',
    categoria: 'Teclado',
    estado: 'ABERTA',
    valorOrcamento: null,
  },
  {
    id: 10,
    dataHoraAbertura: '2026-04-01T13:50:00',
    descricaoEquipamento: 'Dell Optiplex',
    categoria: 'Desktop',
    estado: 'ORCADA',
    valorOrcamento: 760,
  },
];
