import type { SolicitacaoResumo } from './solicitacao.service';

export const SOLICITACOES_DEMO: SolicitacaoResumo[] = [
  {
    id: 1,
    dataHoraAbertura: '2026-01-12T14:10:00',
    descricaoEquipamento: 'Lenovo ThinkPad',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
  },
  {
    id: 2,
    dataHoraAbertura: '2026-01-20T10:00:00',
    descricaoEquipamento: 'Dell XPS 13',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 1100,
  },
  {
    id: 3,
    dataHoraAbertura: '2026-02-05T08:40:00',
    descricaoEquipamento: 'PC Gamer Ryzen',
    categoria: 'Desktop',
    estado: 'ABERTA',
    valorOrcamento: null,
  },
  {
    id: 4,
    dataHoraAbertura: '2026-02-08T09:45:00',
    descricaoEquipamento: 'Brother DCP',
    categoria: 'Impressora',
    estado: 'PAGA',
    valorOrcamento: 270,
  },
  {
    id: 5,
    dataHoraAbertura: '2026-02-10T09:12:00',
    descricaoEquipamento: 'Macbook M1 Pro',
    categoria: 'Notebook',
    estado: 'ABERTA',
    valorOrcamento: null,
  },
  {
    id: 6,
    dataHoraAbertura: '2026-02-12T11:30:00',
    descricaoEquipamento: 'Acer Aspire 5',
    categoria: 'Notebook',
    estado: 'APROVADA',
    valorOrcamento: 890,
  },
  {
    id: 7,
    dataHoraAbertura: '2026-02-14T15:05:00',
    descricaoEquipamento: 'Keychron K2',
    categoria: 'Teclado',
    estado: 'ARRUMADA',
    valorOrcamento: 210,
  },
  {
    id: 8,
    dataHoraAbertura: '2026-02-16T18:20:00',
    descricaoEquipamento: 'HP Pavilion',
    categoria: 'Desktop',
    estado: 'FINALIZADA',
    valorOrcamento: 450,
  },
  {
    id: 9,
    dataHoraAbertura: '2026-02-19T19:47:00',
    descricaoEquipamento: 'ASUS ROG Zephyrus',
    categoria: 'Notebook',
    estado: 'ORCADA',
    valorOrcamento: 1250,
  },
  {
    id: 10,
    dataHoraAbertura: '2026-02-21T17:10:00',
    descricaoEquipamento: 'Teclado mecanico',
    categoria: 'Teclado',
    estado: 'ORCADA',
    valorOrcamento: 180,
  },
  {
    id: 11,
    dataHoraAbertura: '2026-02-27T16:55:00',
    descricaoEquipamento: 'iMac 24',
    categoria: 'Desktop',
    estado: 'ORCADA',
    valorOrcamento: 410,
  },
  {
    id: 12,
    dataHoraAbertura: '2026-03-02T10:15:00',
    descricaoEquipamento: 'Dell Optiplex',
    categoria: 'Desktop',
    estado: 'PAGA',
    valorOrcamento: 980,
  },
  {
    id: 13,
    dataHoraAbertura: '2026-03-04T12:00:00',
    descricaoEquipamento: 'Mouse sem fio',
    categoria: 'Mouse',
    estado: 'APROVADA',
    valorOrcamento: 150,
  },
  {
    id: 14,
    dataHoraAbertura: '2026-03-08T14:40:00',
    descricaoEquipamento: 'HP LaserJet',
    categoria: 'Impressora',
    estado: 'REDIRECIONADA',
    valorOrcamento: 320,
  },
  {
    id: 15,
    dataHoraAbertura: '2026-03-11T16:22:00',
    descricaoEquipamento: 'Logitech MX',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 180,
  },
  {
    id: 16,
    dataHoraAbertura: '2026-03-15T11:25:00',
    descricaoEquipamento: 'Epson EcoTank',
    categoria: 'Impressora',
    estado: 'ARRUMADA',
    valorOrcamento: 390,
  },
  {
    id: 17,
    dataHoraAbertura: '2026-03-22T19:18:00',
    descricaoEquipamento: 'Apple Magic Mouse',
    categoria: 'Mouse',
    estado: 'REJEITADA',
    valorOrcamento: 240,
  },
  {
    id: 18,
    dataHoraAbertura: '2026-03-29T10:08:00',
    descricaoEquipamento: 'Canon Pixma',
    categoria: 'Impressora',
    estado: 'ARRUMADA',
    valorOrcamento: 520,
  },
  {
    id: 19,
    dataHoraAbertura: '2026-04-03T08:30:00',
    descricaoEquipamento: 'Logitech MX Keys',
    categoria: 'Teclado',
    estado: 'REDIRECIONADA',
    valorOrcamento: 330,
  },
  {
    id: 20,
    dataHoraAbertura: '2026-04-06T15:33:00',
    descricaoEquipamento: 'Samsung Galaxy Book',
    categoria: 'Notebook',
    estado: 'FINALIZADA',
    valorOrcamento: 300,
  },
];
